apiVersion: v1
appVersion: 1.0.0
description: A Helm chart for Kubernetes to deploy Prometheus-CachetHQ
home: https://github.com/oxyno-zeta/prometheus-cachethq
maintainers:
  - email: havrileckalexandre@gmail.com
    name: oxyno-zeta
name: prometheus-cachethq
sources:
  - https://github.com/oxyno-zeta/prometheus-cachethq
version: 1.0.2
